FROM mhart/alpine-node:10 as build

# WORKDIR /www/prisma-cms

# RUN apk add bash mc python3 make g++
RUN apk add bash mc
# RUN apk add --upgrade --no-cache vips-dev build-base \
#   --repository https://alpine.global.ssl.fastly.net/alpine/v3.10/community/

WORKDIR /www/boilerplate/

# VOLUME ["/www/nwb/@prisma-cms/docker/prisma-cms/prisma-cms/"]


# Copy all files to the working directly, build the application
# and purge the development dependencies
COPY ./boilerplate .

RUN yarn install --ignore-engines


# RUN yarn
# RUN yarn build

# # RUN npm run build

# EXPOSE 3000

# Start the server for Next.js using Node.js
# CMD ["yarn", "start"]

# USER node